class Found_Solution extends Exception {
}
